# task config
task: hierarchical_singlecombat_shoot

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 1000             # episode length: 200s
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.0,
      ic_lat_geod_deg: 60.0,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0,
      ic_u_fps: 800.0,
    },
    missile: 2
  },
  B0100: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_lat_geod_deg: 60.2,
      ic_long_gc_deg: 120.0,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,  # 英尺/秒
    },
    missile: 2,
  }
}
max_attack_angle: 35        # unit: degree
max_attack_distance: 14000  # unit: m
min_attack_interval: 25     # unit: step

#Dmkmin=6000
#Dmmax=14000
#Dmkmax=10000
#Dmmin=4000
#自己加的
no_esp_angle: 20
max_search_angle: 65
optimal_air_combat_speed: 320
optimal_air_combat_height: 15
max_missile_attack_distance: 14000
max_missile_no_esp_distance: 10000
min_missile_no_esp_distance: 6000
min_missile_attack_distance: 4000
max_radar_search_distance: 25000


# (lontitude, latitude, altitude)
battle_field_center: [120.0, 60.0, 0.0]

# reward config
MissilePostureReward_scale: 30

PostureReward_scale: 15.0
PostureReward_potential: true
PostureReward_orientation_version: v2
PostureReward_range_version: v3

AltitudeReward_safe_altitude: 4.0
AltitudeReward_danger_altitude: 3.5
AltitudeReward_Kv: 0.2

EventDrivenReward_scale: 1
EventDrivenReward_potential: true

MyShootPenaltyReward_scale: 2.0
#MyShootPenaltyReward_potential: true

DistanceReward_scale: 1

VelocityReward_scale: 1

AngelReward_scale: 1

HeightReward_scale: 1