# task config
task: hierarchical_singlecombat_shoot

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 4000          # episode length: 200s
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.0,
      ic_lat_geod_deg: 60.0,
      ic_h_sl_ft: 25000,
      ic_psi_true_deg: 0,
      ic_u_fps: 900.0,
    },
    missile: 2
  },
  B0100: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 25000,
      ic_lat_geod_deg: 60.3,
      ic_long_gc_deg: 120.0,
      ic_psi_true_deg: 0,
      ic_u_fps: 700.0,  # 英尺/秒
    },
    missile: 2,
  }
}

#Dmkmin=6000
#Dmmax=14000
#Dmkmax=10000
#Dmmin=4000
#自己加的

optimal_air_combat_height: 5000
max_missile_attack_distance: 300000
min_missile_attack_distance: 40000


# (lontitude, latitude, altitude)
battle_field_center: [123.4, 26.5, 0.0]

# reward config
MissilePostureReward_scale: 30

PostureReward_scale: 15.0
PostureReward_potential: true
PostureReward_orientation_version: v2
PostureReward_range_version: v3

AltitudeReward_safe_altitude: 4.0
AltitudeReward_danger_altitude: 3.5
AltitudeReward_Kv: 0.2

EventDrivenReward_scale: 1
EventDrivenReward_potential: true